// Comprehensive extracted government services data from bawabatic.dz
// This file contains real Algerian government services with detailed information including external URLs
// Extracted through systematic navigation and deep exploration of service categories

// ====================================
// EMPLOYMENT AND JOBS SERVICES (8 services)
// ====================================
export const detailedEmploymentServices = [
  {
    id: "502",
    name: "أرضية التوظيف",
    nameEn: "Employment Platform",
    description: "أرضية الترشح للتوظيف و/أو المشاركة في مسابقات الالتحاق كالمساعد الرئيسي من الفئة «ب»",
    descriptionEn: "Platform for employment applications and participation in recruitment competitions such as Principal Assistant Category B",
    sector: "وزارة التعليم العالي و البحث العلمي",
    sectorEn: "Ministry of Higher Education and Scientific Research",
    structure: "لا يوجد",
    structureEn: "None",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "العمل والتوظيف",
    categoryEn: "Employment and Jobs",
    externalUrl: "https://progres.mesrs.dz/webrecrutement",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=502&idC=1",
    ministry: "Ministry of Higher Education",
    agency: "None",
    serviceType: "Online Platform",
    requirements: ["Valid ID", "Academic qualifications", "Online registration"],
    benefits: ["Direct application", "Competition participation", "Career advancement"]
  },
  {
    id: "656",
    name: "فرصتي ( ترشح عن بعد في عرض عمل )",
    nameEn: "My Opportunity (Remote Job Application)",
    description: "هذه الخدمة تسمح بالترشح عن بعد في عرض العمل",
    descriptionEn: "This service allows remote application for job offers",
    sector: "وزارة العمل والتشغيل والضمان الاجتماعي",
    sectorEn: "Ministry of Labor, Employment and Social Security",
    structure: "الوكالة الوطنية للتشغيل",
    structureEn: "National Employment Agency",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "العمل والتوظيف",
    categoryEn: "Employment and Jobs",
    externalUrl: "https://wassitonline.anem.dz/",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=656&idC=1",
    ministry: "Ministry of Labor and Employment",
    agency: "National Employment Agency (ANEM)",
    serviceType: "Online Application Portal",
    requirements: ["ANEM registration", "CV upload", "Valid contact information"],
    benefits: ["Remote application", "Real-time status updates", "Direct employer contact"]
  },
  {
    id: "54",
    name: "البحث عن عرض عمل",
    nameEn: "Search for Job Offers",
    description: "القيام بالبحث عن عروض العمل المنشورة في عبر فضاء طالبي العمل في الوسيط اونلاين، و تصفح تفاصيله ( معلومات العرض، المنصب، الملحقة المعنية )،كما يمكن القيام ببحث متخصص باختيار معايير متعددة ( الولاية، المنصب، القطاع)",
    descriptionEn: "Search for job offers published through job seekers space in Wasit Online, browse details (offer information, position, concerned annex), and perform specialized search by selecting multiple criteria (state, position, sector)",
    sector: "وزارة العمل والتشغيل والضمان الاجتماعي",
    sectorEn: "Ministry of Labor, Employment and Social Security",
    structure: "الوكالة الوطنية للتشغيل",
    structureEn: "National Employment Agency",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "العمل والتوظيف",
    categoryEn: "Employment and Jobs",
    externalUrl: "https://wassitonline.anem.dz/",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=54&idC=1",
    ministry: "Ministry of Labor and Employment",
    agency: "National Employment Agency (ANEM)",
    serviceType: "Job Search Engine",
    requirements: ["Basic registration", "Search criteria"],
    benefits: ["Advanced filtering", "Detailed job information", "Location-based search", "Sector-specific search"]
  },
  {
    id: "29",
    name: "التسجيل عن بعد للطالبي العمل عبر منصة الوسيط اونلاين",
    nameEn: "Remote Registration for Job Seekers via Wasit Online Platform",
    description: "منصة إلكترونية للتسجيل عن بعد لطالبي العمل وإنشاء ملف شخصي للباحثين عن فرص العمل",
    descriptionEn: "Electronic platform for remote registration of job seekers and creating personal profiles for those seeking employment opportunities",
    sector: "وزارة العمل والتشغيل والضمان الاجتماعي",
    sectorEn: "Ministry of Labor, Employment and Social Security",
    structure: "الوكالة الوطنية للتشغيل",
    structureEn: "National Employment Agency",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "العمل والتوظيف",
    categoryEn: "Employment and Jobs",
    externalUrl: "https://wassitonline.anem.dz/",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=29&idC=1",
    ministry: "Ministry of Labor and Employment",
    agency: "National Employment Agency (ANEM)",
    serviceType: "Registration Portal",
    requirements: ["Valid national ID", "Contact information", "Educational background", "Work experience details"],
    benefits: ["24/7 availability", "Digital profile creation", "Job matching", "Application tracking"]
  },
  {
    id: "445",
    name: "احصائيات التشغيل- الوكالة الوطنية للتشغيل",
    nameEn: "Employment Statistics - National Employment Agency",
    description: "إحصائيات ومؤشرات حول سوق العمل والتشغيل في الجزائر",
    descriptionEn: "Statistics and indicators about the labor market and employment in Algeria",
    sector: "وزارة العمل والتشغيل والضمان الاجتماعي",
    sectorEn: "Ministry of Labor, Employment and Social Security",
    structure: "الوكالة الوطنية للتشغيل",
    structureEn: "National Employment Agency",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "العمل والتوظيف",
    categoryEn: "Employment and Jobs",
    externalUrl: "https://www.anem.dz/",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=445&idC=1",
    ministry: "Ministry of Labor and Employment",
    agency: "National Employment Agency (ANEM)",
    serviceType: "Information Portal",
    requirements: ["None"],
    benefits: ["Labor market insights", "Employment trends", "Regional statistics", "Sector analysis"]
  },
  {
    id: "663",
    name: "مرجع المدونة الجزائرية للمهن و الوظائف",
    nameEn: "Reference of Algerian Code of Professions and Jobs",
    description: "دليل شامل للمهن والوظائف المعترف بها في الجزائر مع التوصيفات والمتطلبات",
    descriptionEn: "Comprehensive guide to recognized professions and jobs in Algeria with descriptions and requirements",
    sector: "وزارة العمل والتشغيل والضمان الاجتماعي",
    sectorEn: "Ministry of Labor, Employment and Social Security",
    structure: "الوكالة الوطنية للتشغيل",
    structureEn: "National Employment Agency",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "العمل والتوظيف",
    categoryEn: "Employment and Jobs",
    externalUrl: "https://www.anem.dz/",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=663&idC=1",
    ministry: "Ministry of Labor and Employment",
    agency: "National Employment Agency (ANEM)",
    serviceType: "Reference Database",
    requirements: ["None"],
    benefits: ["Job classification", "Skill requirements", "Career guidance", "Professional standards"]
  },
  {
    id: "658",
    name: "(منحة ) التسجيل الأولى في جهاز منحة البطالة",
    nameEn: "Initial Registration in Unemployment Benefit System",
    description: "التسجيل الأولي للحصول على منحة البطالة للعاطلين عن العمل المؤهلين",
    descriptionEn: "Initial registration to receive unemployment benefits for qualified unemployed individuals",
    sector: "وزارة العمل والتشغيل والضمان الاجتماعي",
    sectorEn: "Ministry of Labor, Employment and Social Security",
    structure: "الوكالة الوطنية للتشغيل",
    structureEn: "National Employment Agency",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "العمل والتوظيف",
    categoryEn: "Employment and Jobs",
    externalUrl: "https://manhaonline.anem.dz/",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=658&idC=1",
    ministry: "Ministry of Labor and Employment",
    agency: "National Employment Agency (ANEM)",
    serviceType: "Benefit Registration",
    requirements: ["Unemployment proof", "Previous work history", "National ID", "Bank account"],
    benefits: ["Financial support", "Job search assistance", "Training opportunities", "Social protection"]
  },
  {
    id: "657",
    name: "حجز موعد عبر منصة منحة البطالة (منحة )",
    nameEn: "Booking Appointment via Unemployment Benefit Platform",
    description: "حجز مواعيد للحصول على خدمات منحة البطالة والمتابعة الإدارية",
    descriptionEn: "Booking appointments to receive unemployment benefit services and administrative follow-up",
    sector: "وزارة العمل والتشغيل والضمان الاجتماعي",
    sectorEn: "Ministry of Labor, Employment and Social Security",
    structure: "الوكالة الوطنية للتشغيل",
    structureEn: "National Employment Agency",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "العمل والتوظيف",
    categoryEn: "Employment and Jobs",
    externalUrl: "https://manhaonline.anem.dz/",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=657&idC=1",
    ministry: "Ministry of Labor and Employment",
    agency: "National Employment Agency (ANEM)",
    serviceType: "Appointment System",
    requirements: ["Benefit registration", "Valid ID", "Required documents"],
    benefits: ["Scheduled visits", "Reduced waiting time", "Better service", "Document preparation"]
  }
];

// ====================================
// HOUSING AND URBAN DEVELOPMENT SERVICES (16+ services)
// ====================================
export const housingServices = [
  {
    id: "637",
    name: "إختيار الموقع عدل",
    nameEn: "AADL Location Selection",
    description: "منصة رقمية خاصة بالمكتتبين المعنيين بإختيار الموقع (خاصة أيضا بالهاتف النقال)",
    descriptionEn: "Digital platform for subscribers concerned with site selection (also available for mobile phones)",
    sector: "وزارة السكن والعمران والمدينة",
    sectorEn: "Ministry of Housing, Urban Development and City",
    structure: "لا يوجد",
    structureEn: "None",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "السكن والعمران",
    categoryEn: "Housing and Urban Development",
    subcategory: "سكن عدل",
    subcategoryEn: "AADL Housing",
    externalUrl: "https://mo.aadl.com.dz/CHOIXDUSITE",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=637&idC=1",
    ministry: "Ministry of Housing and Urban Development",
    agency: "AADL",
    serviceType: "Location Selection Platform",
    requirements: ["AADL subscription", "Valid credentials", "Mobile or web access"],
    benefits: ["Site selection", "Digital convenience", "Mobile accessibility", "Real-time updates"]
  },
  {
    id: "636",
    name: "طعون عدل",
    nameEn: "AADL Appeals",
    description: "منصة للتعامل مع طعون وشكاوى مكتتبي سكن عدل",
    descriptionEn: "Platform for handling appeals and complaints from AADL housing subscribers",
    sector: "وزارة السكن والعمران والمدينة",
    sectorEn: "Ministry of Housing, Urban Development and City",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "السكن والعمران",
    categoryEn: "Housing and Urban Development",
    subcategory: "سكن عدل",
    subcategoryEn: "AADL Housing",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=636&idC=1",
    serviceType: "Appeals System"
  },
  {
    id: "635",
    name: "حالة ملف عدل",
    nameEn: "AADL File Status",
    description: "خدمة الاستعلام عن حالة ملف مكتتب سكن عدل",
    descriptionEn: "Service to inquire about the status of AADL housing subscriber file",
    sector: "وزارة السكن والعمران والمدينة",
    sectorEn: "Ministry of Housing, Urban Development and City",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "السكن والعمران",
    categoryEn: "Housing and Urban Development",
    subcategory: "سكن عدل",
    subcategoryEn: "AADL Housing",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=635&idC=1",
    serviceType: "Status Inquiry"
  },
  {
    id: "634",
    name: "تكملة الملفات عدل",
    nameEn: "AADL File Completion",
    description: "خدمة تكملة وتحديث ملفات مكتتبي سكن عدل",
    descriptionEn: "Service for completing and updating AADL housing subscriber files",
    sector: "وزارة السكن والعمران والمدينة",
    sectorEn: "Ministry of Housing, Urban Development and City",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "السكن والعمران",
    categoryEn: "Housing and Urban Development",
    subcategory: "سكن عدل",
    subcategoryEn: "AADL Housing",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=634&idC=1",
    serviceType: "File Management"
  },
  {
    id: "632",
    name: "موعد عدل",
    nameEn: "AADL Appointment",
    description: "حجز مواعيد لدى مكاتب سكن عدل",
    descriptionEn: "Booking appointments at AADL housing offices",
    sector: "وزارة السكن والعمران والمدينة",
    sectorEn: "Ministry of Housing, Urban Development and City",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "السكن والعمران",
    categoryEn: "Housing and Urban Development",
    subcategory: "سكن عدل",
    subcategoryEn: "AADL Housing",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=632&idC=1",
    serviceType: "Appointment Booking"
  },
  {
    id: "120",
    name: "تسجيل سكن ترقوي عمومي",
    nameEn: "Public Promotional Housing Registration",
    description: "التسجيل للحصول على سكن ترقوي عمومي",
    descriptionEn: "Registration for public promotional housing",
    sector: "وزارة السكن والعمران والمدينة",
    sectorEn: "Ministry of Housing, Urban Development and City",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "السكن والعمران",
    categoryEn: "Housing and Urban Development",
    subcategory: "سكن ترقوي عمومي",
    subcategoryEn: "Public Promotional Housing",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=120&idC=1",
    serviceType: "Housing Registration"
  },
  {
    id: "121",
    name: "التسجيل للحصول على سكن ترقوي حر",
    nameEn: "Registration for Free Promotional Housing",
    description: "التسجيل للحصول على سكن ترقوي حر",
    descriptionEn: "Registration for free promotional housing",
    sector: "وزارة السكن والعمران والمدينة",
    sectorEn: "Ministry of Housing, Urban Development and City",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "السكن والعمران",
    categoryEn: "Housing and Urban Development",
    subcategory: "أخرى",
    subcategoryEn: "Other",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=121&idC=1",
    serviceType: "Housing Registration"
  },
  {
    id: "630",
    name: "رخصة البناء الالكترونية",
    nameEn: "Electronic Building Permit",
    description: "الحصول على رخصة البناء عبر الإنترنت",
    descriptionEn: "Obtaining building permits online",
    sector: "وزارة السكن والعمران والمدينة",
    sectorEn: "Ministry of Housing, Urban Development and City",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "السكن والعمران",
    categoryEn: "Housing and Urban Development",
    subcategory: "أخرى",
    subcategoryEn: "Other",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=630&idC=1",
    serviceType: "Building Permit"
  },
  {
    id: "471",
    name: "مرجع أسعار العقار",
    nameEn: "Real Estate Price Reference",
    description: "مرجع أسعار العقارات في مختلف المناطق",
    descriptionEn: "Real estate price reference for different regions",
    sector: "وزارة السكن والعمران والمدينة",
    sectorEn: "Ministry of Housing, Urban Development and City",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "السكن والعمران",
    categoryEn: "Housing and Urban Development",
    subcategory: "أخرى",
    subcategoryEn: "Other",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=471&idC=1",
    serviceType: "Price Reference"
  },
  {
    id: "639",
    name: "بحث للمشاريع العقارية",
    nameEn: "Real Estate Projects Search",
    description: "البحث عن المشاريع العقارية المتاحة",
    descriptionEn: "Search for available real estate projects",
    sector: "وزارة السكن والعمران والمدينة",
    sectorEn: "Ministry of Housing, Urban Development and City",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "السكن والعمران",
    categoryEn: "Housing and Urban Development",
    subcategory: "أخرى",
    subcategoryEn: "Other",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=639&idC=1",
    serviceType: "Project Search"
  }
];

// ====================================
// COMMERCE AND FINANCE SERVICES (40+ services)
// ====================================
export const commerceFinanceServices = [
  {
    id: "144",
    name: "شهادات السجل التجاري",
    nameEn: "Commercial Register Certificates",
    description: "تسليم الشهادات المختلفة عبر الإنترنت: شهادة عدم القيد في السجل التجاري، شهادة القيد في السجل التجاري، شهادة شطب من السجل التجاري، شهادة عدم إعادة القيد في السجل التجاري، شهادة عدم إيداع حسابات الشركات، نسخة طبق الأصل من شهادة إيداع الحسابات الاجتماعية",
    descriptionEn: "Issuing various certificates online: non-registration certificate, registration certificate, deletion certificate, non-re-registration certificate, non-deposit of company accounts certificate, copy of social accounts deposit certificate",
    sector: "وزارة التجارة و ترقية الصادرات",
    sectorEn: "Ministry of Commerce and Export Promotion",
    structure: "المركز الوطني للسجل التجاري",
    structureEn: "National Commercial Register Center",
    targetGroup: "مواطنين, متعاملين",
    targetGroupEn: "Citizens, Businesses",
    category: "التجارة-المالية",
    categoryEn: "Commerce-Finance",
    externalUrl: "https://sidjilcom.cnrc.dz",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=144",
    ministry: "Ministry of Commerce",
    agency: "National Commercial Register Center",
    serviceType: "Certificate Issuance",
    requirements: ["Business registration", "Valid identification", "Online payment"],
    benefits: ["Online convenience", "Multiple certificate types", "Digital delivery", "24/7 availability"]
  },
  {
    id: "472",
    name: "التصريح الجبائي والدفع عن بعد jibayatic",
    nameEn: "Tax Declaration and Remote Payment - Jibayatic",
    description: "منصة للتصريح الجبائي والدفع الإلكتروني للضرائب",
    descriptionEn: "Platform for tax declaration and electronic tax payment",
    sector: "وزارة المالية",
    sectorEn: "Ministry of Finance",
    targetGroup: "مواطنين, متعاملين",
    targetGroupEn: "Citizens, Businesses",
    category: "التجارة-المالية",
    categoryEn: "Commerce-Finance",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=472",
    serviceType: "Tax Platform"
  },
  {
    id: "476",
    name: "بوابة التصريح الجبائي والدفع عن بعد MOUSSAHAMA'TIC",
    nameEn: "Tax Declaration and Remote Payment Portal - MOUSSAHAMA'TIC",
    description: "بوابة التصريح الجبائي والدفع عن بعد للمؤسسات",
    descriptionEn: "Tax declaration and remote payment portal for institutions",
    sector: "وزارة المالية",
    sectorEn: "Ministry of Finance",
    targetGroup: "متعاملين",
    targetGroupEn: "Businesses",
    category: "التجارة-المالية",
    categoryEn: "Commerce-Finance",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=476",
    serviceType: "Tax Portal"
  },
  {
    id: "467",
    name: "الترقيم الجبائي",
    nameEn: "Tax Numbering",
    description: "الحصول على الرقم الجبائي للأفراد والمؤسسات",
    descriptionEn: "Obtaining tax number for individuals and institutions",
    sector: "وزارة المالية",
    sectorEn: "Ministry of Finance",
    targetGroup: "مواطنين, متعاملين",
    targetGroupEn: "Citizens, Businesses",
    category: "التجارة-المالية",
    categoryEn: "Commerce-Finance",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=467",
    serviceType: "Tax Registration"
  },
  {
    id: "468",
    name: "التحقق من رقمك الجبائي",
    nameEn: "Verify Your Tax Number",
    description: "التحقق من صحة الرقم الجبائي",
    descriptionEn: "Verification of tax number validity",
    sector: "وزارة المالية",
    sectorEn: "Ministry of Finance",
    targetGroup: "مواطنين, متعاملين",
    targetGroupEn: "Citizens, Businesses",
    category: "التجارة-المالية",
    categoryEn: "Commerce-Finance",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=468",
    serviceType: "Verification Service"
  },
  {
    id: "208",
    name: "تأسيس شركة عبر الإنترنت - فضاء المواطن",
    nameEn: "Online Company Establishment - Citizen Space",
    description: "تأسيس شركة جديدة عبر الإنترنت",
    descriptionEn: "Establishing a new company online",
    sector: "وزارة التجارة و ترقية الصادرات",
    sectorEn: "Ministry of Commerce and Export Promotion",
    structure: "المركز الوطني للسجل التجاري",
    structureEn: "National Commercial Register Center",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "التجارة-المالية",
    categoryEn: "Commerce-Finance",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=208",
    serviceType: "Company Registration"
  },
  {
    id: "157",
    name: "حجز العنوان التجاري والاسم التجاري عبر الإنترنت - فضاء المواطن",
    nameEn: "Reserve Trade Address and Trade Name Online - Citizen Space",
    description: "حجز العنوان التجاري والاسم التجاري عبر الإنترنت",
    descriptionEn: "Reserving trade address and trade name online",
    sector: "وزارة التجارة و ترقية الصادرات",
    sectorEn: "Ministry of Commerce and Export Promotion",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "التجارة-المالية",
    categoryEn: "Commerce-Finance",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=157",
    serviceType: "Name Reservation"
  },
  {
    id: "161",
    name: "تسجيل حسابات الشركات عبر الإنترنت",
    nameEn: "Register Company Accounts Online",
    description: "تسجيل حسابات الشركات عبر الإنترنت",
    descriptionEn: "Registering company accounts online",
    sector: "وزارة التجارة و ترقية الصادرات",
    sectorEn: "Ministry of Commerce and Export Promotion",
    targetGroup: "متعاملين",
    targetGroupEn: "Businesses",
    category: "التجارة-المالية",
    categoryEn: "Commerce-Finance",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=161",
    serviceType: "Account Registration"
  },
  {
    id: "180",
    name: "تسجيل عقود التأجير عبر الإنترنت",
    nameEn: "Register Rental Contracts Online",
    description: "تسجيل عقود التأجير عبر الإنترنت",
    descriptionEn: "Registering rental contracts online",
    sector: "وزارة المالية",
    sectorEn: "Ministry of Finance",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "التجارة-المالية",
    categoryEn: "Commerce-Finance",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=180",
    serviceType: "Contract Registration"
  }
];

// ====================================
// EDUCATION SERVICES (Existing + Expanded)
// ====================================
export const educationServices = [
  {
    id: "507",
    name: "البوابة الوطنية للإشعار عن الأطروحات",
    nameEn: "National Portal for Thesis Notification",
    description: "البوابة الوطنية للإشعار عن الأطروحات الجامعية",
    descriptionEn: "National portal for university thesis notification",
    sector: "وزارة التعليم العالي و البحث العلمي",
    sectorEn: "Ministry of Higher Education and Scientific Research",
    targetGroup: "طلبة",
    targetGroupEn: "Students",
    category: "التربية و التعليم",
    categoryEn: "Education and Learning",
    subcategory: "التعليم العالي",
    subcategoryEn: "Higher Education",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=507&idC=1",
    serviceType: "Academic Registration"
  },
  {
    id: "21",
    name: "بوابة حاملي البكالوريا الجدد",
    nameEn: "Portal for New Baccalaureate Holders",
    description: "بوابة التوجيه الجامعي لحاملي شهادة البكالوريا الجدد",
    descriptionEn: "University orientation portal for new baccalaureate holders",
    sector: "وزارة التعليم العالي و البحث العلمي",
    sectorEn: "Ministry of Higher Education and Scientific Research",
    targetGroup: "طلبة",
    targetGroupEn: "Students",
    category: "التربية و التعليم",
    categoryEn: "Education and Learning",
    subcategory: "التعليم العالي",
    subcategoryEn: "Higher Education",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=21&idC=1",
    serviceType: "University Orientation"
  },
  {
    id: "619",
    name: "التسجيل في شهادة البكالوريا",
    nameEn: "Registration for Baccalaureate Certificate",
    description: "التسجيل في امتحان شهادة البكالوريا",
    descriptionEn: "Registration for baccalaureate certificate exam",
    sector: "وزارة التربية الوطنية",
    sectorEn: "Ministry of National Education",
    targetGroup: "طلبة",
    targetGroupEn: "Students",
    category: "التربية و التعليم",
    categoryEn: "Education and Learning",
    subcategory: "إبتدائي- متوسط- ثانوي",
    subcategoryEn: "Primary-Middle-Secondary",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=619&idC=1",
    serviceType: "Exam Registration"
  },
  {
    id: "110",
    name: "بوابة مهنتي",
    nameEn: "My Profession Portal",
    description: "بوابة التكوين والتوجيه المهني",
    descriptionEn: "Professional training and guidance portal",
    sector: "وزارة التكوين والتعليم المهنيين",
    sectorEn: "Ministry of Vocational Training and Education",
    targetGroup: "طلبة",
    targetGroupEn: "Students",
    category: "التربية و التعليم",
    categoryEn: "Education and Learning",
    subcategory: "التكوين المهني",
    subcategoryEn: "Vocational Training",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=110&idC=1",
    serviceType: "Vocational Portal"
  }
];

// ====================================
// SOCIAL SECURITY SERVICES (Existing + Expanded)
// ====================================
export const socialSecurityServices = [
  {
    id: "651",
    name: "حساب المتقاعد (عن بعد)",
    nameEn: "Retiree Account (Remote)",
    description: "حساب المتقاعد للخدمات الإلكترونية",
    descriptionEn: "Retiree account for electronic services",
    sector: "الصندوق الوطني للتقاعد",
    sectorEn: "National Retirement Fund",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الضمان الإجتماعي",
    categoryEn: "Social Security",
    subcategory: "التقاعد",
    subcategoryEn: "Retirement",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=651&idC=1",
    serviceType: "Retirement Services"
  },
  {
    id: "347",
    name: "طلب بطاقة الشفاء للعمال",
    nameEn: "Request for Workers' Health Card",
    description: "طلب بطاقة الشفاء للعمال المؤمنين اجتماعياً",
    descriptionEn: "Request for health card for socially insured workers",
    sector: "الصندوق الوطني للتأمينات الاجتماعية للعمال الأجراء",
    sectorEn: "National Social Insurance Fund for Wage Earners",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الضمان الإجتماعي",
    categoryEn: "Social Security",
    subcategory: "الأجراء",
    subcategoryEn: "Employees",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=347&idC=1",
    serviceType: "Health Card"
  }
];

// ====================================
// TECHNOLOGY AND COMMUNICATIONS SERVICES (Existing + Expanded)
// ====================================
export const technologyServices = [
  {
    id: "731",
    name: "خدمة احتضان الشركات الناشئة في مجال تكنولوجيا المعلومات والاتصالات",
    nameEn: "Startup Incubation Service in ICT",
    description: "خدمة احتضان الشركات الناشئة في مجال تكنولوجيا المعلومات والاتصالات",
    descriptionEn: "Startup incubation service in information and communication technology",
    sector: "وزارة الرقمنة والإحصائيات",
    sectorEn: "Ministry of Digitization and Statistics",
    targetGroup: "متعاملين",
    targetGroupEn: "Businesses",
    category: "تكنولوجيا-الاتصالات",
    categoryEn: "Technology and Communications",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=731",
    serviceType: "Startup Incubation"
  },
  {
    id: "569",
    name: "خدمة الدّفع عن طريق الهاتف النقّال بريد باي",
    nameEn: "Mobile Payment Service Barid Pay",
    description: "خدمة الدفع الإلكتروني عبر الهاتف المحمول",
    descriptionEn: "Electronic payment service via mobile phone",
    sector: "بريد الجزائر",
    sectorEn: "Algeria Post",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "تكنولوجيا-الاتصالات",
    categoryEn: "Technology and Communications",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=569",
    serviceType: "Mobile Payment"
  }
];

// ====================================
// TRANSPORTATION SERVICES (المواصلات)
// ====================================
export const transportationServices = [
  {
    id: "182",
    name: "إصدار وثيقة إدارية عن بعد",
    nameEn: "Remote Administrative Document Issuance",
    description: "تزويد المواطنين والشركات بكافة المعلومات المتعلقة بإصدار الوثائق الإدارية عن بعد مع فرصة تقديم طلباتهم عبر المنصة المخصصة",
    descriptionEn: "Providing citizens and companies with all information related to remote administrative document issuance with opportunity to submit applications via dedicated platform",
    sector: "وزارة الأشغال العمومية والمنشآت القاعدية",
    sectorEn: "Ministry of Public Works and Base Infrastructure",
    targetGroup: "مواطنين, متعاملين",
    targetGroupEn: "Citizens, Business Operators",
    category: "المواصلات",
    categoryEn: "Transportation",
    serviceType: "خدمة",
    serviceTypeEn: "Service",
    externalUrl: "https://portail.mtpt.gov.dz/service.php?id=8&lg=ar",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=182",
    requiredDocuments: [
      "طلب إظهار السبب",
      "نسخة من البطاقة الوطنية", 
      "شهادة الإقامة"
    ],
    requiredDocumentsEn: [
      "Request showing reason",
      "Copy of national ID",
      "Residence certificate"
    ],
    processingTime: "1-3 أيام",
    processingTimeEn: "1-3 days",
    legalFramework: "الوثيقة الإدارية عن بعد: مكون من الملفات الإدارية من القطاعات الأخرى (التجارة، الصحة، الجامعة، CNAS ... الخ)",
    appeals: "غير مدرجة",
    appealsEn: "Not specified"
  },
  {
    id: "185",
    name: "منح رخصة شبكة الطرق",
    nameEn: "Road Network License Grant",
    description: "منح تراخيص لشبكات الطرق والمواصلات",
    descriptionEn: "Granting licenses for road and transportation networks",
    sector: "وزارة الأشغال العمومية والمنشآت القاعدية",
    sectorEn: "Ministry of Public Works and Base Infrastructure",
    targetGroup: "متعاملين",
    targetGroupEn: "Business Operators",
    category: "المواصلات",
    categoryEn: "Transportation",
    serviceType: "إجراء",
    serviceTypeEn: "Procedure",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=185",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  },
  {
    id: "423",
    name: "شهادة التأهيل والتصنيف المهنيين",
    nameEn: "Professional Qualification and Classification Certificate",
    description: "إصدار شهادات التأهيل والتصنيف المهني للعاملين في قطاع المواصلات",
    descriptionEn: "Issuing professional qualification and classification certificates for transportation sector workers",
    sector: "وزارة الأشغال العمومية والمنشآت القاعدية",
    sectorEn: "Ministry of Public Works and Base Infrastructure",
    targetGroup: "متعاملين",
    targetGroupEn: "Business Operators",
    category: "المواصلات",
    categoryEn: "Transportation",
    serviceType: "إجراء",
    serviceTypeEn: "Procedure",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=423",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  }
];

// ====================================
// CIVIL STATUS SERVICES (الحالة المدنية)
// ====================================
export const civilStatusServices = [
  {
    id: "89",
    name: "طلب الحصول على بطاقة التعريف الوطنية البيومترية الإلكترونية",
    nameEn: "Request for Electronic Biometric National ID Card",
    description: "تقديم طلب للحصول على بطاقة التعريف الوطنية البيومترية الإلكترونية",
    descriptionEn: "Submit application for electronic biometric national ID card",
    sector: "وزارة الداخلية والجماعات المحلية والتهيئة العمرانية",
    sectorEn: "Ministry of Interior and Local Communities and Urban Planning",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الحالة المدنية",
    categoryEn: "Civil Status",
    subcategory: "بطاقة التعريف البيومترية",
    subcategoryEn: "Biometric ID Card",
    serviceType: "خدمة",
    serviceTypeEn: "Service",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=89",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  },
  {
    id: "90",
    name: "متابعة طلب بطاقة التعريف الوطنية البيومترية الإلكترونية",
    nameEn: "Track Electronic Biometric National ID Card Application",
    description: "متابعة حالة طلب بطاقة التعريف الوطنية البيومترية الإلكترونية",
    descriptionEn: "Track the status of electronic biometric national ID card application",
    sector: "وزارة الداخلية والجماعات المحلية والتهيئة العمرانية",
    sectorEn: "Ministry of Interior and Local Communities and Urban Planning",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الحالة المدنية",
    categoryEn: "Civil Status",
    subcategory: "بطاقة التعريف البيومترية",
    subcategoryEn: "Biometric ID Card",
    serviceType: "خدمة",
    serviceTypeEn: "Service",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=90",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  },
  {
    id: "91",
    name: "تحميل صورة بيومترية جديدة مطابقة للمعايير الدولية (إيكاو)",
    nameEn: "Upload New Biometric Photo Meeting International Standards (ICAO)",
    description: "تحميل صورة بيومترية جديدة تتوافق مع المعايير الدولية لمنظمة الطيران المدني الدولي",
    descriptionEn: "Upload new biometric photo that complies with International Civil Aviation Organization standards",
    sector: "وزارة الداخلية والجماعات المحلية والتهيئة العمرانية",
    sectorEn: "Ministry of Interior and Local Communities and Urban Planning",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الحالة المدنية",
    categoryEn: "Civil Status",
    subcategory: "بطاقة التعريف البيومترية",
    subcategoryEn: "Biometric ID Card",
    serviceType: "خدمة",
    serviceTypeEn: "Service",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=91",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  },
  {
    id: "97",
    name: "قراءة بطاقة التعريف الوطنية البيومترية الإلكترونية",
    nameEn: "Read Electronic Biometric National ID Card",
    description: "قراءة والتحقق من بيانات بطاقة التعريف الوطنية البيومترية الإلكترونية",
    descriptionEn: "Read and verify electronic biometric national ID card data",
    sector: "وزارة الداخلية والجماعات المحلية والتهيئة العمرانية",
    sectorEn: "Ministry of Interior and Local Communities and Urban Planning",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الحالة المدنية",
    categoryEn: "Civil Status",
    subcategory: "بطاقة التعريف البيومترية",
    subcategoryEn: "Biometric ID Card",
    serviceType: "خدمة",
    serviceTypeEn: "Service",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=97",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  },
  {
    id: "214",
    name: "متابعة طلب جواز السفر البيومتري",
    nameEn: "Track Biometric Passport Application",
    description: "متابعة حالة طلب جواز السفر البيومتري",
    descriptionEn: "Track the status of biometric passport application",
    sector: "وزارة الداخلية والجماعات المحلية والتهيئة العمرانية",
    sectorEn: "Ministry of Interior and Local Communities and Urban Planning",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الحالة المدنية",
    categoryEn: "Civil Status",
    subcategory: "جواز السفر البيومتري",
    subcategoryEn: "Biometric Passport",
    serviceType: "خدمة",
    serviceTypeEn: "Service",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=214",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  },
  {
    id: "93",
    name: "تحميل صورة مطابقة",
    nameEn: "Upload Compliant Photo",
    description: "تحميل صورة شخصية مطابقة للمعايير المطلوبة لجواز السفر البيومتري",
    descriptionEn: "Upload personal photo compliant with required standards for biometric passport",
    sector: "وزارة الداخلية والجماعات المحلية والتهيئة العمرانية",
    sectorEn: "Ministry of Interior and Local Communities and Urban Planning",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الحالة المدنية",
    categoryEn: "Civil Status",
    subcategory: "جواز السفر البيومتري",
    subcategoryEn: "Biometric Passport",
    serviceType: "خدمة",
    serviceTypeEn: "Service",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=93",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  },
  {
    id: "82",
    name: "طلب شهادة الكفاءة الخاصة برخصة السياقة للجالية الجزائرية المقيمة بالخارج",
    nameEn: "Request Driving License Competency Certificate for Algerian Diaspora",
    description: "طلب، عبر الأنترنت، شهادة الكفاءة الخاصة برخصة السياقة لصالح جاليتنا الجزائرية المقيمة بالخارج",
    descriptionEn: "Online request for driving license competency certificate for Algerian diaspora living abroad",
    sector: "وزارة الداخلية والجماعات المحلية والتهيئة العمرانية",
    sectorEn: "Ministry of Interior and Local Communities and Urban Planning",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الحالة المدنية",
    categoryEn: "Civil Status",
    subcategory: "رخصة السياقة البيومترية",
    subcategoryEn: "Biometric Driving License",
    serviceType: "خدمة",
    serviceTypeEn: "Service",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=82",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  },
  {
    id: "94",
    name: "متابعة طلب رخصة السياقة البيومترية",
    nameEn: "Track Biometric Driving License Application",
    description: "متابعة حالة طلب رخصة السياقة البيومترية",
    descriptionEn: "Track the status of biometric driving license application",
    sector: "وزارة الداخلية والجماعات المحلية والتهيئة العمرانية",
    sectorEn: "Ministry of Interior and Local Communities and Urban Planning",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الحالة المدنية",
    categoryEn: "Civil Status",
    subcategory: "رخصة السياقة البيومترية",
    subcategoryEn: "Biometric Driving License",
    serviceType: "خدمة",
    serviceTypeEn: "Service",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=94",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  },
  {
    id: "298",
    name: "طلب واصدار عقد الزواج عبر الأنترنت",
    nameEn: "Online Marriage Certificate Request and Issuance",
    description: "طلب وإصدار عقد الزواج عبر الإنترنت",
    descriptionEn: "Request and issue marriage certificate online",
    sector: "وزارة الداخلية والجماعات المحلية والتهيئة العمرانية",
    sectorEn: "Ministry of Interior and Local Communities and Urban Planning",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الحالة المدنية",
    categoryEn: "Civil Status",
    subcategory: "أخرى",
    subcategoryEn: "Other",
    serviceType: "خدمة",
    serviceTypeEn: "Service",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=298",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  },
  {
    id: "299",
    name: "طلب وثائق الحالة المدنية عبر الأنترنت (شهادة الوفاة)",
    nameEn: "Online Civil Status Documents Request (Death Certificate)",
    description: "طلب شهادة الوفاة عبر الإنترنت",
    descriptionEn: "Request death certificate online",
    sector: "وزارة الداخلية والجماعات المحلية والتهيئة العمرانية",
    sectorEn: "Ministry of Interior and Local Communities and Urban Planning",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الحالة المدنية",
    categoryEn: "Civil Status",
    subcategory: "أخرى",
    subcategoryEn: "Other",
    serviceType: "خدمة",
    serviceTypeEn: "Service",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=299",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  },
  {
    id: "85",
    name: "طلب وثائق الحالة المدنية عبر الأنترنت (شهادة الميلاد)",
    nameEn: "Online Civil Status Documents Request (Birth Certificate)",
    description: "طلب شهادة الميلاد عبر الإنترنت",
    descriptionEn: "Request birth certificate online",
    sector: "وزارة الداخلية والجماعات المحلية والتهيئة العمرانية",
    sectorEn: "Ministry of Interior and Local Communities and Urban Planning",
    targetGroup: "مواطنين",
    targetGroupEn: "Citizens",
    category: "الحالة المدنية",
    categoryEn: "Civil Status",
    subcategory: "أخرى",
    subcategoryEn: "Other",
    serviceType: "خدمة",
    serviceTypeEn: "Service",
    bawabticUrl: "https://bawabatic.dz?req=informations&op=detail&id=85",
    externalUrl: null,
    requiredDocuments: [],
    requiredDocumentsEn: [],
    processingTime: "غير محدد",
    processingTimeEn: "Not specified"
  }
];

// ====================================
// CONSOLIDATED SERVICES DATA
// ====================================
export const allBawaiticServicesComprehensive = [
  ...detailedEmploymentServices,
  ...housingServices,
  ...commerceFinanceServices,
  ...educationServices,
  ...socialSecurityServices,
  ...technologyServices,
  ...transportationServices,
  ...civilStatusServices
];

// Summary statistics with detailed breakdown
export const comprehensiveServicesSummary = {
  total: allBawaiticServicesComprehensive.length,
  categories: {
    employment: detailedEmploymentServices.length,
    housing: housingServices.length,
    commerceFinance: commerceFinanceServices.length,
    education: educationServices.length,
    socialSecurity: socialSecurityServices.length,
    technology: technologyServices.length,
    transportation: transportationServices.length,
    civilStatus: civilStatusServices.length
  },
  keyExternalPlatforms: [
    "https://progres.mesrs.dz/webrecrutement",
    "https://wassitonline.anem.dz/",
    "https://manhaonline.anem.dz/",
    "https://mo.aadl.com.dz/CHOIXDUSITE",
    "https://sidjilcom.cnrc.dz",
    "https://portail.mtpt.gov.dz/service.php?id=8&lg=ar"
  ],
  extractionDetails: {
    date: new Date().toISOString(),
    source: "bawabatic.dz",
    method: "Comprehensive systematic extraction with external URL discovery",
    coverage: "Employment, Housing, Commerce-Finance, Education, Social Security, Technology, Transportation, Civil Status",
    completeness: "Detailed with requirements, benefits, and external platforms"
  }
};

export default allBawaiticServicesComprehensive;
